#!/bin/bash

# 获取 `panelcnv` 真实所在目录
script_path="$(readlink -f "$0")"
script_dir="$(dirname "$script_path")"

# 定义子命令
case "$1" in
    alignment)
        echo "[INFO] Running alignment..."
        bash "$script_dir/alignment.sh" "${@:2}"  # 传递除第一个参数外的所有参数
        ;;
    
    bqsr)
        echo "[INFO] Running BQSR..."
        bash "$script_dir/bqsr.sh" "${@:2}"
        ;;

    preprocessing)
        echo "[INFO] Running preprocessing..."
        bash "$script_dir/preprocessing.sh" "${@:2}"
        ;;
        
    deduplicate)
        echo "[INFO] Running deduplication..."
        bash "$script_dir/deduplication.sh" "${@:2}"
        ;;
        
    cnv_calling)
        echo "[INFO] Running CNV calling..."
        bash "$script_dir/../cnv_calling_main.sh" "${@:2}"
        ;;

    help|--help|-h)
        echo "Usage: panelcnv <command> [options]"
        echo "Commands:"
        echo "  alignment      Run alignment pipeline"
        echo "  bqsr           Run Base Quality Score Recalibration (BQSR)"
        echo "  preprocessing  Run preprocessing steps"
        echo "  filter         Run filtering scripts"
        echo "  cnv_calling    Run CNV calling pipeline"
        echo "  help           Show this help message"
        ;;

    *)
        echo "[ERROR] Unknown command: $1"
        echo "Use 'panelcnv help' to see available commands."
        exit 1
        ;;
esac

